---
name: hephaestus
services:
  bot:
    container_name: Hephaestus-bot
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - Hephaestus-db:/app/db/
volumes:
  Hephaestus-db:
