---
name: hephaestus
services:

  bot:
    container_name: Hephaestus-bot
    build:
      context: bot/.
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - bot:/srv/database

#  docker compose up -d --no-deps --build stale-pr-alerts cat-fact