---
name: hephaestus
services:
  bot:
    container_name: Hephaestus-bot
    build:
      context: bot/.
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - Hephaestus-db:/app/db/
volumes:
  Hephaestus-db:

#  docker compose up -d --no-deps --build stale-pr-alerts cat-fact