name: TestPR

on:
  pull_request:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install check-manifest
        run: pip install check-manifest
      - name: Run check-manifest
        run: check-manifest --ignore 'tox.ini,tests/**,.editorconfig,vscode.env,.vscode/**'
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py
